### ISSUE TITLE
Error installing the Dynu add-on

### ISSUE THREAD

**Issue by Lumute** [koying/ha-addons#1]
Hi, i just tried to install the Dynu Add-on and get this error after pressing the install button:

Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache openssl && curl -s -o /usr/bin/dehydrated "https://raw.githubusercontent.com/lukas2511/dehydrated/v${DEHYDRATED_VERSION}/dehydrated" && chmod a+x /usr/bin/dehydrated' returned a non-zero code: 1

This is on a Raspberry Pi 4 with latest Raspberry OS 64 bit and Home Assistant installed in Supervisor mode...

**Comment by Lumute** [comment]
This is the longer error:

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)

ERROR: unable to select packages:

  openssl (no such package):
    required by: world[openssl]
Removing intermediate container a5ed79f43908

21-09-26 21:16:03 INFO (SyncWorker_3) [supervisor.docker.addon] Starting build for 4e8751bd/armv7-addon-dynudns:1.0.0
21-09-26 21:16:05 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build 4e8751bd/armv7-addon-dynudns:1.0.0: The command '/bin/ash -o pipefail -c apk add --no-cache openssl   && curl -s -o /usr/bin/dehydrated     "https://raw.githubusercontent.com/lukas2511/dehydrated/v${DEHYDRATED_VERSION}/dehydrated"   && chmod a+x /usr/bin/dehydrated' returned a non-zero code: 1
21-09-26 21:16:05 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/12 : ARG BUILD_FROM
Step 2/12 : FROM $BUILD_FROM
 ---> a6b4abf955c9
Step 3/12 : ARG DEHYDRATED_VERSION
 ---> Using cache
 ---> 77ead6168a16
Step 4/12 : RUN apk add --no-cache openssl   && curl -s -o /usr/bin/dehydrated     "https://raw.githubusercontent.com/lukas2511/dehydrated/v${DEHYDRATED_VERSION}/dehydrated"   && chmod a+x /usr/bin/dehydrated
 ---> [Warning] The requested image's platform (linux/arm) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 43816983e050
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)

ERROR: unable to select packages:

  openssl (no such package):
    required by: world[openssl]
Removing intermediate container 43816983e050

**Comment by koying** [comment]
I assume this is a supervised install?
There is a known issue when building addons on rspbian, but I thought it was limited to 32bits.

Anyway, you can check https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771/15?u=koying and see if it helps...

**Comment by Lumute** [comment]
That fixed it, thanks a lot!
