### ISSUE TITLE
Add-on crashed & set IP check isn‘t working

### ISSUE THREAD

**Issue by h1nnak** [koying/ha-addons#11]
Hey there,

the Add-on crashed sometimes. The second Problem is, I cant set the seconds to check a new IP. It remains at a 12-hour interval. 

Debug Log will be submitted later:
`# INFO: Using main config file /data/workdir/config
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 6)
EXPECTED value GOT EOF`

`s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by DeveloperSG** [comment]
+1, happened on my installation couple of times already
