### ISSUE TITLE
IPv6 not working

### ISSUE THREAD

**Issue by McGiverGim** [koying/ha-addons#12]
Hi! I'm trying to use this addon. I've one little problem: the ipv6 is not detected.
The curl command is not working from inside the docker of the addon:
```
curl -s -f -m 10 "https://ipv6.text.wtfismyip.com/"
curl: (7) Failed to connect to ipv6.text.wtfismyip.com port 443 after 3 ms: Couldn't connect to server

```

But if I execute the same command in the bash of the Home Assistant, it works. I suppose this does not work because the IPv6 must be attached to the container, and this docker does not have one, or don't have permissions or something. But if it has one, it will not work neither, because it will be different than the IPv6 of the Home Assistant docker, that is what we want.

Looking at the DuckDNS addon, I see this code:
https://github.com/home-assistant/addons/blob/133709534a0bc853ee93a2315657b59caa67ca0e/duckdns/data/run.sh#L71-L82

That I suppose that tries to obtain the ipv6 from host interface.

**Comment by koying** [comment]
Should be fixed by https://github.com/koying/ha-addons/pull/14
