### ISSUE TITLE
Dynu addon re-sets the settings from dynu.com website

### ISSUE THREAD

**Issue by OscarHanzely** [koying/ha-addons#3]
I have a dynu addon installed and configured. It works as expected.

Until you change anything on the main site. I turned on the "Wildcard IPv4 Alias"  in the configuration of the duny.com profile for that domain. It works for a while but then something resets the value to off. I suspect its the dynu addon during its API call must be sending other values hardcoded.

How can I even configure the addon to send the values or can we please not override the configuration stored online?

I tried to set it up as an alias, with the wildcard `*.<domain>` but every time I restart the addon it disables it on dynu site again. It just shows it red immediately when sync happens. 
![image](https://user-images.githubusercontent.com/39314151/151679996-c2590f2d-fa41-49ef-b9ed-7748c531da2c.png)

**Comment by koying** [comment]
Did you modify the domain name of the addon to make it wildcard one?

Not sure it will work, but it will surely not if you don't try that.

**Comment by koying** [comment]
Did you configure the same in the addon configuration?

Not sure it will work, though. I never tested that.

**Comment by OscarHanzely** [comment]
I did configure it in the configuration under aliases as a wildcard. I see
it in dynu.com records the only problem is something is constantly turning
records off. not removing just shutting down.

**Comment by koying** [comment]
Should be fixed by https://github.com/koying/ha-addons/pull/14
