### ISSUE TITLE
Addon fails to start: s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by clmattm** [koying/ha-addons#4]
Addon no longer works after recent update to home assistant.

https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by shawnyo** [comment]
I am also having this issue. Any ideas?

**Comment by MamafPadi** [comment]
Broken due to update, needs init command to be used afaik.

**Comment by MamafPadi** [comment]
Same issue here. s6-overlay-suexec: fatal: can only run as pid 1

**Comment by vlatkojordanov90** [comment]
hey man, are you willing to do a fix on this? https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by mhart505** [comment]
Can we please get this fixed??

**Comment by MamafPadi** [comment]
still no joy, certificates almost useless.. thanks Koying

**Comment by zerocritical** [comment]
Same issue.. I cant even find config.yaml to think about fix

**Comment by h3nrytan** [comment]
@zerocritical hello. may i know how you edit the config.json file? i could not locate.

**Comment by MamafPadi** [comment]
@zerocritical i hope he responds, it's been very silent. How exactly did you edit those files? I'm quite the programming novice xD

**Comment by zerocritical** [comment]
I created a local copy of the addon by downloading the files and placing it in the addons folder. Once in addons folder, edited the files in that folder. Hope this helps.

**Comment by MamafPadi** [comment]
and now i cant access home assistant.. fun

**Comment by loocd** [comment]
Would be amazing if those commits could be merged in order to fix the addon.
Or any  why that you, @zerocritical could provide the addon for us to use?

**Comment by pauldanieltudor** [comment]
@zerocritical you rock ! I got stuck at the idea of "local addons", so in more detail: uninstall the addon, copy the files to addons folder in HA and then in addons store you will find it first as a local addon to install, click install and then re-configure it to point to your dynu dns domain you created along with API key as token again, mine started working and all looks good, restart HA to be sure certificate is updated. Keep in mind you need to reconfigure everything that was linked to that ddns address: alexa, google, anything else linked manually.

**Comment by marsonwar** [comment]
They have been merged, i tested and it's working.
I guess this could be marked as Done?

**Comment by pauldanieltudor** [comment]
Ideally the author would correct the addon first, it is just 3 lines, without this page it would end up in the bin. Issue is still present unless it got updated in last 7 days.

**Comment by marsonwar** [comment]
Well... he did 6 days ago... Just didn't close the issues.
But they are Fixed\Merged.
