### ISSUE TITLE
Does not work if your own domain name is used.

### ISSUE THREAD

**Issue by PramodAryalGithub** [koying/ha-addons#9]
It works fine if free dynu domain name is used. However if you have your own domain setup in dynu, it does not work.

Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by PramodAryalGithub** [comment]
It turned out to be due to difference between domain and hostname. I was trying to create multiple subdomain from my main domain. HA was going to be running in a subdomain.

This implementation does not support for subdomain option.  Also adding wild card support to include all subdomain to LetsEncrypt would be great.

**Comment by vittorio88** [comment]
@PramodAryalGithub Would you mind sharing how you determined that the implementation does not support subdomains?

**Comment by koying** [comment]
Should be fixed by https://github.com/koying/ha-addons/pull/14
